name: Build and Package

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install Rust nightly
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: nightly
        override: true

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Install npm dependencies
      run: |
        cd tauri-app
        npm install

    - name: Run package script
      run: python package.py

    - name: Upload Tauri artifacts
      uses: actions/upload-artifact@v3
      with:
        name: tauri-release
        path: tauri-app/src-tauri/target/release/bundle/
